import 'dotenv/config';
import * as fs from 'fs/promises';
import * as fsSync from 'fs';
import * as path from 'path';
import * as os from 'os';
import { execSync } from 'child_process';
import matter from 'gray-matter';
import { PortfolioFrontmatterSchema } from '../src/lib/portfolio/schema';
import type { PortfolioProject, PortfolioData } from '../src/lib/portfolio/types';

const GITHUB_API = 'https://api.github.com';
const GITHUB_USER = 'RCushmaniii';
const SELF_REPO = 'ai-portfolio';
const SYNC_LABEL = 'portfolio-sync';
const OUTPUT_PATH = path.join(process.cwd(), 'content', 'portfolio.json');

interface SyncIssue {
  level: 'error' | 'warning';
  repo: string;
  message: string;
}
const syncIssues: SyncIssue[] = [];

interface GitHubRepo {
  name: string;
  html_url: string;
  description: string | null;
  language: string | null;
  stargazers_count: number;
  forks_count: number;
  updated_at: string;
  topics: string[];
  private: boolean;
}

async function fetchUserRepos(token: string): Promise<GitHubRepo[]> {
  const repos: GitHubRepo[] = [];
  let page = 1;

  while (true) {
    const response = await fetch(
      `${GITHUB_API}/user/repos?per_page=100&page=${page}&sort=updated&affiliation=owner`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github.v3+json',
          'User-Agent': 'portfolio-sync-script',
        },
      }
    );

    if (!response.ok) {
      if (response.status === 401) throw new Error('Invalid GitHub token');
      if (response.status === 403) throw new Error('Rate limit exceeded');
      throw new Error(`GitHub API error: ${response.status}`);
    }

    const data = await response.json();
    if (data.length === 0) break;
    repos.push(...data); // Include all repos (public and private)
    page++;
    if (page > 10) break;
  }

  return repos;
}

async function fetchPortfolioMd(repoName: string, token: string): Promise<string | null> {
  // Try both casings — GitHub Contents API is case-sensitive
  for (const filename of ['PORTFOLIO.md', 'portfolio.md']) {
    const response = await fetch(
      `${GITHUB_API}/repos/${GITHUB_USER}/${repoName}/contents/${filename}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github.v3.raw',
          'User-Agent': 'portfolio-sync-script',
        },
      }
    );

    if (response.status === 404) continue;
    if (response.status === 403) {
      syncIssues.push({ level: 'error', repo: repoName, message: '403 Forbidden — token lacks access to this repo' });
      return null;
    }
    if (!response.ok) throw new Error(`Failed to fetch: ${response.status}`);
    return response.text();
  }

  return null;
}

// ---------------------------------------------------------------------------
// GitHub Issue reporting — persistent notifications for sync problems
// Uses gh CLI for write operations (fine-grained tokens lack issue write scope)
// ---------------------------------------------------------------------------

const GH_REPO_FLAG = `--repo ${GITHUB_USER}/${SELF_REPO}`;

function gh(args: string): string {
  return execSync(`gh ${args}`, { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
}

/** Write body to a temp file for gh --body-file (avoids shell escaping issues) */
function withBodyFile(body: string, fn: (filePath: string) => string): string {
  const tmpFile = path.join(os.tmpdir(), `sync-issue-${Date.now()}.md`);
  fsSync.writeFileSync(tmpFile, body, 'utf-8');
  try {
    return fn(tmpFile);
  } finally {
    fsSync.unlinkSync(tmpFile);
  }
}

function findExistingSyncIssue(): number | null {
  try {
    // Search for open issues with the portfolio-sync label
    const result = gh(`issue list ${GH_REPO_FLAG} --label "${SYNC_LABEL}" --state open --json number --limit 1`);
    const issues = JSON.parse(result);
    if (issues.length > 0) return issues[0].number;
  } catch {
    // Label search failed — try title-based fallback
  }

  try {
    const result = gh(`issue list ${GH_REPO_FLAG} --state open --search "Portfolio Sync: in:title" --json number --limit 1`);
    const issues = JSON.parse(result);
    if (issues.length > 0) return issues[0].number;
  } catch {
    // Title search also failed
  }

  return null;
}

function buildIssueBody(issues: SyncIssue[]): string {
  const errors = issues.filter(i => i.level === 'error');
  const warnings = issues.filter(i => i.level === 'warning');
  const timestamp = new Date().toISOString();

  const groupByRepo = (items: SyncIssue[]) => {
    const grouped: Record<string, string[]> = {};
    for (const item of items) {
      if (!grouped[item.repo]) grouped[item.repo] = [];
      grouped[item.repo].push(item.message);
    }
    return grouped;
  };

  let body = `> Auto-generated by \`sync-portfolio.ts\` at ${timestamp}\n\n`;

  if (errors.length > 0) {
    body += `## Errors (${errors.length})\n\n`;
    const grouped = groupByRepo(errors);
    for (const [repo, msgs] of Object.entries(grouped)) {
      body += `### \`${repo}\`\n`;
      for (const msg of msgs) body += `- ${msg}\n`;
      body += '\n';
    }
  }

  if (warnings.length > 0) {
    body += `## Warnings (${warnings.length})\n\n`;
    const grouped = groupByRepo(warnings);
    for (const [repo, msgs] of Object.entries(grouped)) {
      body += `### \`${repo}\`\n`;
      for (const msg of msgs) body += `- ${msg}\n`;
      body += '\n';
    }
  }

  body += `## How to Fix\n\n`;
  body += `- **403 Forbidden**: Check that your \`GITHUB_TOKEN\` has \`public_repo\` scope and access to the repo.\n`;
  body += `- **Invalid frontmatter**: Open the repo's \`PORTFOLIO.md\` and fix the YAML fields flagged above.\n`;
  body += `- **Missing fields**: Add the missing content to the repo's \`PORTFOLIO.md\` frontmatter.\n`;
  body += `- **No slides/screenshots**: Add \`hero_images\` to the frontmatter or place images in the repo.\n\n`;
  body += `This issue will auto-close when a clean sync run completes with no issues.\n`;

  return body;
}

function reportSyncIssues(issues: SyncIssue[]): void {
  try {
    const errors = issues.filter(i => i.level === 'error').length;
    const warnings = issues.filter(i => i.level === 'warning').length;
    const date = new Date().toISOString().split('T')[0];
    const title = `Portfolio Sync: ${errors} error(s), ${warnings} warning(s) — ${date}`;
    const body = buildIssueBody(issues);

    const existing = findExistingSyncIssue();

    if (existing) {
      // Update existing issue: add comment with latest report + update title
      withBodyFile(body, (f) => gh(`issue comment ${existing} ${GH_REPO_FLAG} --body-file "${f}"`));
      gh(`issue edit ${existing} ${GH_REPO_FLAG} --title ${JSON.stringify(title)}`);
      console.log(`\n📋 Updated GitHub Issue #${existing}: ${title}`);
    } else {
      // Create new issue with label
      const result = withBodyFile(body, (f) =>
        gh(`issue create ${GH_REPO_FLAG} --title ${JSON.stringify(title)} --body-file "${f}" --label "${SYNC_LABEL}"`)
      );
      const match = result.match(/\/issues\/(\d+)/);
      const num = match ? `#${match[1]}` : '';
      console.log(`\n📋 Created GitHub Issue ${num}: ${title}`);
    }
  } catch (err) {
    console.warn(`\n⚠️  Could not report sync issues to GitHub: ${err instanceof Error ? err.message : err}`);
  }
}

function closeResolvedIssue(): void {
  try {
    const existing = findExistingSyncIssue();
    if (!existing) return;

    gh(`issue comment ${existing} ${GH_REPO_FLAG} --body "✅ All sync issues resolved as of ${new Date().toISOString()}. Closing automatically."`);
    gh(`issue close ${existing} ${GH_REPO_FLAG}`);
    console.log(`\n📋 Closed GitHub Issue #${existing} — all issues resolved`);
  } catch (err) {
    console.warn(`\n⚠️  Could not close resolved GitHub Issue: ${err instanceof Error ? err.message : err}`);
  }
}

async function main() {
  const token = process.env.GITHUB_TOKEN || process.env.PROJECT_SYNC_TOKEN;
  if (!token) {
    console.error('❌ GITHUB_TOKEN or PROJECT_SYNC_TOKEN environment variable is required');
    process.exit(1);
  }

  console.log('🔄 Starting portfolio sync...\n');

  const repos = await fetchUserRepos(token);
  const privateCount = repos.filter(r => r.private).length;
  console.log(`📦 Found ${repos.length} repositories (${privateCount} private)\n`);

  const projects: PortfolioProject[] = [];

  for (const repo of repos) {
    process.stdout.write(`  ${repo.name}: `);

    try {
      const content = await fetchPortfolioMd(repo.name, token);

      if (!content) {
        console.log('⏭️  No PORTFOLIO.md');
        continue;
      }

      const { data: frontmatter, content: body } = matter(content);
      const result = PortfolioFrontmatterSchema.safeParse(frontmatter);

      if (!result.success) {
        console.log('❌ Invalid frontmatter');
        const details = result.error.issues.map(i => `${i.path.join('.')}: ${i.message}`).join('; ');
        syncIssues.push({ level: 'error', repo: repo.name, message: `Invalid frontmatter — ${details}` });
        result.error.issues.forEach((issue) => {
          console.log(`     - ${issue.path.join('.')}: ${issue.message}`);
        });
        continue;
      }

      if (!result.data.portfolio_enabled) {
        console.log('⏭️  Disabled');
        continue;
      }

      const project: PortfolioProject = {
        ...result.data,
        body_markdown: body.trim(),
        repo_name: repo.name,
        repo_url: repo.html_url,
        thumbnail_fallback: `https://opengraph.githubassets.com/1/RCushmaniii/${repo.name}`,
        github_stars: repo.stargazers_count,
        github_forks: repo.forks_count,
        github_language: repo.language,
        github_updated_at: repo.updated_at,
        github_description: repo.description || '',
        github_topics: repo.topics || [],
      };

      // Quality checks — warnings only, project still gets added
      if (!project.tagline)                 syncIssues.push({ level: 'warning', repo: repo.name, message: 'Missing tagline' });
      if (!project.thumbnail)               syncIssues.push({ level: 'warning', repo: repo.name, message: 'Missing thumbnail' });
      if (project.tech_stack.length === 0)  syncIssues.push({ level: 'warning', repo: repo.name, message: 'Empty tech stack' });
      if (!project.problem)                 syncIssues.push({ level: 'warning', repo: repo.name, message: 'Missing problem/challenge description' });
      if (project.hero_images.length === 0) syncIssues.push({ level: 'warning', repo: repo.name, message: 'No portfolio slides/screenshots' });

      projects.push(project);
      console.log('✅ Added');
    } catch (error) {
      console.log(`❌ Error: ${error instanceof Error ? error.message : error}`);
    }
  }

  projects.sort((a, b) => a.portfolio_priority - b.portfolio_priority);

  const output: PortfolioData = {
    generated_at: new Date().toISOString(),
    projects,
  };

  await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  await fs.writeFile(OUTPUT_PATH, JSON.stringify(output, null, 2), 'utf-8');

  console.log(`\n📄 Wrote to: ${OUTPUT_PATH}`);
  console.log(`✅ Sync complete: ${projects.length} projects`);

  // Report sync issues to GitHub Issues
  if (syncIssues.length > 0) {
    const errors = syncIssues.filter(i => i.level === 'error').length;
    const warnings = syncIssues.filter(i => i.level === 'warning').length;
    console.log(`\n⚠️  ${syncIssues.length} sync issue(s): ${errors} error(s), ${warnings} warning(s)`);
    reportSyncIssues(syncIssues);
  } else {
    console.log('\n✅ No sync issues detected');
    closeResolvedIssue();
  }

  console.log('');
}

main().catch(console.error);
